dw_do_zero:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME_PRD') }}"
      host: "{{ env_var('DB_HOST_PRD') }}"
      pass: "{{ env_var('DB_PASS_PRD') }}"
      port: 5432
      schema: "{{ env_var('DB_SCHEMA_PRD') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('DB_USER_PRD') }}"
  target: dev

